apiVersion: v1
kind: Service
metadata:
  name: flaskapi
  namespace: flaskapi
  labels:
    app: flaskapi
spec:
  type: NodePort
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 30101
  selector:
    app: flaskapi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    app: flaskapi
  name: flaskapi
  namespace: flaskapi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flaskapi
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: flaskapi
        version: latest
    spec:
      containers:
      - name: flaskapi
        image: akilada/flaskapi:1.0.3
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20
        resources:
          requests:
            memory: "150Mi"
            cpu: "100m"
          limits:
            memory: "200Mi"
            cpu: "150m"
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: flaskapi
  namespace: flaskapi
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: flaskapi
  minReplicas: 2
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 60